# Generated by Django 5.1.4 on 2025-01-11 17:12

from django.db import migrations, models
from django.contrib.auth.models import User

def get_default_user(apps, schema_editor):
    # This will return the first User in the database, or you can adjust it as needed
    return User.objects.first()  # Make sure this returns a valid user

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_burned', models.FloatField()),
            ],
        ),
    ]
