# Generated by Django 5.1.4 on 2025-01-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitfapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
