# Generated by Django 5.1.4 on 2025-01-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitfapapp', '0002_fooditem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='quantity',
        ),
    ]
