# Generated by Django 5.1.4 on 2025-02-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitfapapp', '0004_usergoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='unit_type',
            field=models.CharField(choices=[('count', 'Count'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters')], default='count', max_length=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.FloatField(help_text='Calories per unit (100g, 100ml, or per count)'),
        ),
    ]
