# Generated by Django 5.1.4 on 2025-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitfapapp', '0005_fooditem_unit_type_alter_fooditem_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='unit_type',
            field=models.CharField(choices=[('count', 'Count'), ('g', 'Grams'), ('ml', 'Milliliters')], default='count', max_length=10),
        ),
    ]
